### ISSUE TITLE
Document Portal broke

### ISSUE THREAD

**Issue by A1ca7raz** [nixpak/nixpak#100]
I made a nixpak package of Obsidian months ago and it worked. But recently I found I cannot call the Document Portal on the host.

https://github.com/A1ca7raz/nurpkgs/blob/main/pkgs/_nixpaks/obsidian/default.nix

**Comment by ccdunder** [comment]
Probably https://github.com/electron/electron/issues/43819

**Comment by ccdunder** [comment]
Yeah, looks like you're packaging obsidian from unstable nixpkgs, which uses electron, which broke support for xdg-portals. The regression in electron reached unstable nixpkgs a couple weeks ago.

The fix at this point is to pull in xdg-desktop-portal 1.19.x (beta) or 1.20.x.

Alternatively you could use electron <31.6 but I don't recommend it since it's using Chrome from June.

**Comment by max-privatevoid** [comment]
Looks like an Electron problem, so nothing we can do here. Depending on an unreleased API version is a pretty wild move tbh. Thanks @ccdunder for investigating.
