### ISSUE TITLE
[Help] Unable to execute Firefox's binary multiple times

### ISSUE THREAD

**Issue by Guanran928** [nixpak/nixpak#41]
Unable to execute Firefox (or Firefox based browser)'s binary multiple times.
In this case, LibreWolf. I tried Firefox as well, no luck.

My [Flake](https://codeberg.org/guanranwang/flake/src/branch/master/users/guanranwang/home-manager/resources/browser/firefox.nix) including nixpak configurations.

I assume it is missing some DBus stuff? Made it working once while messing with DBus policies but it wont work anymore after another rebuild.

![image](https://github.com/nixpak/nixpak/assets/68757440/744550d7-82e1-4317-828f-681fdce60d8d)

**Comment by max-privatevoid** [comment]
Maybe there's another directory that Firefox uses to store some socket or lock file? I had something similar happening with Chromium, had to ensure that all Chromium processes have access to the same /tmp, because the first instance will create an IPC socket in there:
https://github.com/nixpak/pkgs/blob/master/pkgs/browsers/chromium/default.nix#L14-L20

**Comment by Guanran928** [comment]
Apparently those DBus policy works
I tried it before but it wasn't working for some reason ._.
```nix
dbus.policies = {
 "org.mozilla.firefox.*" = "own";        # firefox
 # "org.mozilla.firefox_beta.*" = "own"; # firefox beta (?)
 # "io.gitlab.librewolf.*" = "own";      # librewolf
};
```
