### ISSUE TITLE
nixpak portalized 'save as' dialog doesn't work unless the flatpak version is installed

### ISSUE THREAD

**Issue by crabdancing** [nixpak/nixpak#62]
It's super weird. If I have, say, the flatpak version of Firefox installed, and a nixpak version, the nixpak version will fail to e.g. write to ~/Downloads _unless_ the flatpak version is installed and configured with the same access. I've tried `flatpak override --user --filesystem=xdg-download:rw org.mozilla.firefox` and directly editing `~/.local/share/flatpak` to no avail.

And I've confirmed that, if the flatpak is installed, but e.g. `~/Downloads` is _disabled_, then the Downloads directory access starts to fail again.

This happens both on Plasma 5 and Hyprland, with the portals enabled as recommended. Flatpak seems to work more or less fine, except that saving outside of explicitly allowed directories doesn't seem to work like it should.

Any idea what could possibly cause this?

**Comment by max-privatevoid** [comment]
I happen to know exactly what causes this. I know a hack to make it work, but I haven't found a way to "nicely" integrate this into NixPak itself yet.

This is caused by the XDG Document Portal. When it detects a Flatpak app (NixPak emulates the necessary heuristics), it will call the `flatpak` CLI command to discover the permissions for a given path.

The hack to make it work is to provide a fake `flatpak` CLI that returns the expected values.

https://git.privatevoid.net/max/config/-/blob/master/modules/desktop/nixpak-tricks.nix?ref_type=heads

**Comment by alxpettit** [comment]
Hmm. Any way I can do this without interrupting actual flatpak usage? Maybe I can write a wrapper for `xdg-desktop-portal` for its PATH specifically, and then avoid replacing flatpak generally. I have an idea for a module that could accomplish this, if you're interested in PRs.

**Comment by alxpettit** [comment]
Here's what I ended up with after taking a crack at it: https://github.com/alxpettit/nixpak-flatpak-wrapper

If I try to inject into the PATH, it doesn't seem to work -- which tells me I'm probably wrapping the wrong binaries or something. Regardless, my little flake seems to do the job, and exposes a simple TOML to control the permission overrides. It also doesn't (in my testing) otherwise interfere with Flatpak's normal behavior.

**Comment by alxpettit** [comment]
I cleaned it up. Gonna put it under a dedicated project name and rename some stuff -- maybe get the schemas to cooperate better, and then we should be good? I put it under LGPL license in the hopes that makes the work easier to use, in case you wanted to use it. Let me know what your thoughts are. Prolly at least a few use cases/desires I missed.

**Comment by crabdancing** [comment]
I think I'm happy with my solution. I'll close the issue now. :)
